### ISSUE TITLE
Any plan to release current master to PyPI?

### ISSUE THREAD

**Issue by qinix** [gmr/flatdict#39]

**Comment by gmr** [comment]
4.0 was released today

**Comment by cadyherron** [comment]
I can't install 4.0.0 from PyPI, it's failing with the error `WARNING: Generating metadata for package flatdict produced metadata for project name unknown. Fix your #egg=flatdict fragments.`

I ran these steps with a fresh virtual environment:

-   python3 -m venv .venv
-   source .venv/bin/activate
-   pip install --upgrade pip
-   pip install flatdict

I can still install 3.4.0 with `pip install flatdict==3.4.0`. Screenshot below:

<img width="1263" alt="Screen Shot 2020-02-12 at 2 00 54 PM" src="https://user-images.githubusercontent.com/6027478/74381457-5686c380-4da0-11ea-937b-3d0ed595438a.png">

**Comment by gmr** [comment]
What version of Python are you using?

I think the issue is probably your setuptools version, as it works for me:

(env) gavinr@s1068$ pip install flatdict==4.0.0
Collecting flatdict==4.0.0
  Downloading
https://artifactory.aweber.io/api/pypi/pypi/packages/packages/1c/b9/d230fe2bc5d14322fdf9b8df53b4e2902230d8a66e24cc48eeb46b29fe29/flatdict-4.0.0.tar.gz
Installing collected packages: flatdict
  Running setup.py install for flatdict ... done
Successfully installed flatdict-4.0.0
WARNING: You are using pip version 19.2.3, however version 20.0.2 is
available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) gavinr@s1068$ pip freeze
flatdict==4.0.0

Can you try "pip install --upgrade setuptools", try again and then see if
that fixes your issue?

**Comment by cadyherron** [comment]
I'm using Python 3.6.4. This command did work for me: `pip install --upgrade setuptools`

Thank you!
